name: Static Code Analysis & Formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 pylint mypy bandit 

      - name: Run Black (Auto-format)
        run: black .

      - name: Run isort (Sort imports)
        run: isort . 

      - name: Run Flake8 (PEP8 style guide checker)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Pylint (Code quality checker)
        run: pylint $(git ls-files '*.py')

      - name: Run mypy (Type hint checker)
        run: mypy .

      - name: Run Bandit (Security analyzer)
        run: bandit -r .
      
      - name: Commit changes if any
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-format code with Black and isort" || exit 0
          git push
